
[module]
  [module.hugoVersion]
    extended = false
    min = "0.55.0"
	summaryLength = 10

[taxonomies]
  color = "color"
  categories = "category"

[blackfriday]
    extensions = ["hardLineBreak"]

    [menu]

      [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/mission"
        weight = 10

      [[menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services/fiscal-sponsorship/"
        weight = 20

        [[menu.main]]
          identifier = "projects"
          name = "Projects"
          url = "/projects/project-list"
          weight = 30

      [[menu.main]]
        identifier = "support"
        name = "Support"
        url = "/support/how-to"
        weight = 40

      [[menu.main]]
        identifier = "news"
        name = "News"
        url = "/news"
        weight = 50

      [[menu.main]]
        identifier = "faq"
        name = "FAQ"
        url = "/faq"
        weight = 60
