
[module]
  [module.hugoVersion]
    extended = false
    min = "0.55.0"

[blackfriday]
    extensions = ["hardLineBreak"]

    [menu]

      [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/mission"
        weight = 10

      [[menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services/fiscal-sponsorship"
        weight = 20

        [[menu.main]]
          identifier = "projects"
          name = "Projects"
          url = "/projects/host-project"
          weight = 30

      [[menu.main]]
        identifier = "support"
        name = "Support"
        url = "/support/how-to"
        weight = 40
